---
abstract: 'This module provides an easy to use wrapper around the Net::XMPP class of modules for specific access to GTalk ( Both on Gmail and Google Apps ). '
author:
  - 'Harish Madabushi <harish.tmh@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-XMPP-Client-GTalk
no_index:
  directory:
    - t
    - inc
requires:
  Net::XMPP: 0
  XML::Smart: 0
  perl: 5.006
version: 0.01
